# Generated by Django 5.2 on 2025-06-11 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='limitorder',
            index=models.Index(fields=['ticker', 'direction', 'status', 'price', 'timestamp'], name='limit_order_ticker_d90a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='limitorder',
            index=models.Index(fields=['user'], name='limit_order_user_id_c780bb_idx'),
        ),
        migrations.AddIndex(
            model_name='marketorder',
            index=models.Index(fields=['user'], name='market_orde_user_id_b6d54a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer'], name='transaction_buyer_i_56e41a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller'], name='transaction_seller__083d37_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ticker', 'timestamp'], name='transaction_ticker_5b5a49_idx'),
        ),
    ]
